# Generated by Django 5.2.6 on 2025-09-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='week_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
